#: Fonts {{{

font_family      DinaRemaster
bold_font        DinaRemaster Bold
italic_font      auto
bold_italic_font auto

font_size 12.0

box_drawing_scale 0.001, 1, 1.5, 2

#:}}


#: Theme {{

background #0A0E14
foreground #e5e1cf
cursor #f19618
selection_background #243340
color0 #000000
color8 #323232
color1 #ff3333
color9 #ff6565
color2 #b8cc52
color10 #e9fe83
color3 #e6c446
color11 #fff778
color4 #36a3d9
color12 #68d4ff
color5 #f07078
color13 #ffa3aa
color6 #95e5cb
color14 #c7fffc
color7 #ffffff
color15 #ffffff
selection_foreground #0e1419


#:}}


#: Cursor customization {{{

cursor none
cursor_text_color background
cursor_shape block
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
cursor_blink_interval -1
cursor_stop_blinking_after 15.0

#: }}}


#: Scrollback {{{

scrollback_lines 2000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
scrollback_pager_history_size 0
scrollback_fill_enlarged_window no
wheel_scroll_multiplier 5.0
wheel_scroll_min_lines 1
touch_scroll_multiplier 1.0

#: }}}


#:URL {{{

url_color
url_style curly
open_url_with default
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
detect_urls yes

#: }}}


#: Performance tuning {{{

repaint_delay 10 
input_delay 3
sync_to_monitor yes

#: }}}


#: Keyboard shortcuts {{{

#: especial mod key
kitty_mod ctrl+shift

#: Copy to clipboard
map kitty_mod+c copy_to_clipboard
map cmd+c       copy_to_clipboard

#: Paste from clipboard

map kitty_mod+v paste_from_clipboard
map cmd+v       paste_from_clipboard

#: }}}

shell_integration enabled
